import type { AppRecord, Persona } from './domain';
export const personas: Persona[] = [
    { id: 'architect', name: 'Data architect', role: 'architect', team: 'Data platform', initials: 'DA', domains: { 'Data platform': 1, Manufacturing: .8, Quality: .65, Engineering: .6 }, datasets: ['mart.build', 'mart.certification', 'mart.quality'], recent: ['build-overview', 'data-health', 'part-genealogy'], description: 'Governance, manufacturing visibility, and reliable data.' },
    { id: 'manufacturing', name: 'Manufacturing lead', role: 'manufacturing', team: 'Manufacturing', initials: 'ML', domains: { Manufacturing: 1, Quality: .85, 'Supply chain': .75 }, datasets: ['mart.build', 'mart.work_orders', 'mart.parts'], recent: ['build-overview', 'work-orders', 'material-readiness'], description: 'Build progress, material readiness, and production flow.' },
    { id: 'quality', name: 'Quality engineer', role: 'quality', team: 'Quality', initials: 'QE', domains: { Quality: 1, Manufacturing: .8, Engineering: .7 }, datasets: ['mart.quality', 'mart.parts', 'mart.calibration'], recent: ['quality-signals', 'part-genealogy', 'calibration'], description: 'Nonconformances, traceability, and calibration evidence.' },
    { id: 'new', name: 'New team member', role: 'new', team: 'Engineering', initials: 'NT', domains: { Engineering: .65 }, datasets: [], recent: [], description: 'A cold-start profile with no recorded activity.' }
];
const rows: Omit<AppRecord, 'status'>[] = [
    { id: 'build-overview', name: 'Build overview', domain: 'Manufacturing', summary: 'See every build, its critical path, and what needs attention.', question: 'Which work is putting the next build milestone at risk?', owner: 'Production analytics', tags: ['Build progress', 'Schedule', 'Work orders'], datasets: ['mart.build', 'mart.work_orders'], roles: ['architect', 'manufacturing'], audiences: ['all'], color: '#aa8eff', certified: true, freshness: '12 min ago', metric: { label: 'Milestones on track', value: '87%', change: '+6 pts this week' }, series: [32, 36, 34, 48, 43, 52, 58, 53, 68, 75, 79, 87], weeklyUsers: 142, teamUse: { 'Data platform': 18, Manufacturing: 62, Quality: 21, Engineering: 35 }, historyLabel: 'Viewed recently' },
    { id: 'quality-signals', name: 'Quality signals', domain: 'Quality', summary: 'Follow nonconformances from first signal to verified closure.', question: 'Where are repeat quality issues slowing production?', owner: 'Quality systems', tags: ['NCR', 'Root cause', 'Quality'], datasets: ['mart.quality', 'mart.build'], roles: ['quality', 'manufacturing'], audiences: ['all'], color: '#68ddce', certified: true, freshness: '18 min ago', metric: { label: 'Open nonconformances', value: '24', change: '8 closed this week' }, series: [68, 74, 62, 61, 50, 57, 45, 42, 48, 35, 29, 24], weeklyUsers: 98, teamUse: { 'Data platform': 12, Manufacturing: 31, Quality: 44, Engineering: 11 }, historyLabel: 'Popular with your team' },
    { id: 'material-readiness', name: 'Material readiness', domain: 'Supply chain', summary: 'Connect part availability to the builds that depend on it.', question: 'Which shortages need action before work can start?', owner: 'Supply chain analytics', tags: ['Inventory', 'Suppliers', 'Parts'], datasets: ['mart.parts', 'mart.build'], roles: ['manufacturing'], audiences: ['all'], color: '#edbf73', certified: true, freshness: '2 hours ago', warning: { level: 'warning', title: 'Supplier feed delayed', detail: 'One synthetic supplier feed is 2 hours behind its 30-minute refresh target. Inventory totals may be incomplete.' }, metric: { label: 'Material coverage', value: '92%', change: '3 shortages to review' }, series: [72, 78, 75, 80, 82, 81, 87, 84, 86, 90, 91, 92], weeklyUsers: 115, teamUse: { Manufacturing: 52, Quality: 9, Engineering: 22, 'Data platform': 11 }, historyLabel: 'Used across production' },
    { id: 'data-health', name: 'Data health', domain: 'Data platform', summary: 'Know which tables, pipelines, and reports are ready to trust.', question: 'Which data assets have failed checks or need certification?', owner: 'Data platform', tags: ['Certification', 'Freshness', 'Pipelines'], datasets: ['mart.certification', 'mart.pipeline_runs'], roles: ['architect'], audiences: ['architect', 'manufacturing', 'quality'], color: '#90adff', certified: true, freshness: '5 min ago', metric: { label: 'Checks passing', value: '98.4%', change: '126 certified assets' }, series: [70, 78, 82, 79, 86, 91, 90, 93, 90, 95, 97, 98], weeklyUsers: 57, teamUse: { 'Data platform': 35, Manufacturing: 10, Quality: 12 }, historyLabel: 'Connected to your data' },
    { id: 'part-genealogy', name: 'Part genealogy', domain: 'Manufacturing', summary: 'Trace a part through its suppliers, assemblies, and evidence.', question: 'Which assemblies are affected by this part or lot?', owner: 'Manufacturing systems', tags: ['Traceability', 'Parts', 'Lineage'], datasets: ['mart.parts', 'mart.quality'], roles: ['architect', 'quality', 'manufacturing'], audiences: ['all'], color: '#be91f3', certified: true, freshness: '20 min ago', newApp: true, metric: { label: 'Traceability coverage', value: '96%', change: '+4 pts this month' }, series: [50, 56, 61, 63, 65, 70, 73, 76, 85, 89, 93, 96], weeklyUsers: 72, teamUse: { 'Data platform': 15, Manufacturing: 28, Quality: 26, Engineering: 3 }, historyLabel: 'New in your domains' },
    { id: 'test-explorer', name: 'Test explorer', domain: 'Engineering', summary: 'Explore test runs, sensor trends, and evidence in one place.', question: 'What changed between a successful and an anomalous run?', owner: 'Test engineering', tags: ['Telemetry', 'Test runs', 'Anomalies'], datasets: ['mart.test_runs', 'mart.telemetry'], roles: ['architect', 'quality'], audiences: ['all'], color: '#77c7ef', certified: true, freshness: '9 min ago', metric: { label: 'Runs within envelope', value: '94%', change: '48 synthetic test runs' }, series: [18, 24, 31, 23, 62, 49, 81, 56, 71, 67, 85, 94], weeklyUsers: 86, teamUse: { Engineering: 57, Quality: 17, Manufacturing: 4, 'Data platform': 8 }, historyLabel: 'Explore engineering' },
    { id: 'work-orders', name: 'Work order flow', domain: 'Manufacturing', summary: 'Spot aging work and constraints before the queue grows.', question: 'Where is work waiting, and who can move it forward?', owner: 'Production operations', tags: ['Work orders', 'Throughput', 'Queue'], datasets: ['mart.work_orders', 'mart.build'], roles: ['manufacturing', 'architect'], audiences: ['all'], color: '#a0cd8d', certified: true, freshness: '15 min ago', metric: { label: 'Orders completed', value: '168', change: '+12% this week' }, series: [42, 51, 59, 60, 64, 72, 70, 84, 86, 91, 94, 99], weeklyUsers: 121, teamUse: { Manufacturing: 81, Quality: 16, Engineering: 14, 'Data platform': 10 }, historyLabel: 'Keep work moving' },
    { id: 'calibration', name: 'Calibration watch', domain: 'Quality', summary: 'Connect instrument status to the evidence it supports.', question: 'Which measurements depend on instruments due for calibration?', owner: 'Metrology', tags: ['Calibration', 'Evidence', 'Instruments'], datasets: ['mart.calibration', 'mart.quality'], roles: ['quality', 'architect'], audiences: ['all'], color: '#6abdc7', certified: true, freshness: '32 min ago', metric: { label: 'Instruments current', value: '97%', change: '6 due within 14 days' }, series: [77, 82, 83, 82, 88, 85, 92, 91, 94, 95, 96, 97], weeklyUsers: 39, teamUse: { Quality: 25, Engineering: 8, Manufacturing: 4, 'Data platform': 2 }, historyLabel: 'Related to quality' },
    { id: 'engineering-change', name: 'Change impact', domain: 'Engineering', summary: 'See the parts and work affected by an engineering change.', question: 'What needs to change when a design revision is released?', owner: 'Product engineering', tags: ['PLM', 'Revisions', 'Dependencies'], datasets: ['mart.revisions', 'mart.parts'], roles: ['architect', 'quality', 'manufacturing'], audiences: ['all'], color: '#df9fc3', certified: false, freshness: '1 hour ago', newApp: true, warning: { level: 'notice', title: 'Certification in review', detail: 'This synthetic app is available for exploration. Its business definitions are awaiting owner approval.' }, metric: { label: 'Open change packages', value: '12', change: '4 awaiting disposition' }, series: [25, 35, 22, 30, 40, 48, 35, 27, 20, 25, 15, 12], weeklyUsers: 28, teamUse: { Engineering: 19, Quality: 4, Manufacturing: 3, 'Data platform': 2 }, historyLabel: 'Recently added' },
    { id: 'supplier-pulse', name: 'Supplier pulse', domain: 'Supply chain', summary: 'Track delivery reliability and the parts most exposed to delay.', question: 'Which suppliers are driving late deliveries?', owner: 'Procurement analytics', tags: ['Suppliers', 'Delivery', 'Risk'], datasets: ['mart.suppliers', 'mart.parts'], roles: ['manufacturing'], audiences: ['all'], color: '#d99774', certified: true, freshness: '45 min ago', metric: { label: 'On-time delivery', value: '91%', change: '+3 pts this month' }, series: [71, 77, 74, 80, 81, 80, 84, 89, 85, 88, 90, 91], weeklyUsers: 63, teamUse: { Manufacturing: 34, Engineering: 12, Quality: 11, 'Data platform': 6 }, historyLabel: 'Related to material readiness' },
    { id: 'pipeline-observer', name: 'Pipeline observer', domain: 'Data platform', summary: 'Follow pipeline runs, failures, and downstream impact.', question: 'Which failed jobs are blocking a report refresh?', owner: 'Data engineering', tags: ['Pipelines', 'Lineage', 'Freshness'], datasets: ['mart.pipeline_runs', 'mart.certification'], roles: ['architect'], audiences: ['architect'], color: '#8da5da', certified: true, freshness: '3 min ago', metric: { label: 'Successful runs', value: '99.1%', change: '2 failures to investigate' }, series: [87, 88, 93, 90, 94, 95, 92, 97, 96, 98, 99, 99], weeklyUsers: 24, teamUse: { 'Data platform': 24 }, historyLabel: 'Built for your role' },
    { id: 'build-cost', name: 'Build cost explorer', domain: 'Finance', summary: 'Understand material and labor trends across builds.', question: 'Which cost categories are changing as build volume grows?', owner: 'Finance analytics', tags: ['Cost', 'Labor', 'Materials'], datasets: ['mart.build_cost', 'mart.build'], roles: ['architect', 'manufacturing'], audiences: ['architect', 'manufacturing'], color: '#c6b984', certified: true, freshness: '1 day ago', metric: { label: 'Cost versus plan', value: '−4.2%', change: 'Within planning range' }, series: [92, 85, 80, 84, 74, 77, 69, 67, 66, 59, 61, 57], weeklyUsers: 44, teamUse: { 'Data platform': 7, Manufacturing: 22, Finance: 15 }, historyLabel: 'Cross-domain discovery' },
    { id: 'legacy-tracker', name: 'Legacy schedule tracker', domain: 'Manufacturing', summary: 'A superseded scheduling application.', question: 'What was the original schedule?', owner: 'Production analytics', tags: ['Legacy'], datasets: ['mart.build'], roles: [], audiences: ['all'], color: '#999999', certified: false, freshness: 'Unavailable', warning: { level: 'critical', title: 'Retired app', detail: 'Use Build overview instead.' }, metric: { label: 'Status', value: 'Retired', change: '' }, series: [], weeklyUsers: 0, teamUse: {}, historyLabel: '' }
];
export const catalog: AppRecord[] = rows.map(({ ...x }) => ({ ...x, status: x.id === 'legacy-tracker' ? 'retired' : 'active' }));
export function personaFor(id: string | undefined) { return personas.find(p => p.id === id) ?? personas[0]; }
export function eligible(app: AppRecord, persona: Persona) { return app.status === 'active' && app.warning?.level !== 'critical' && (app.audiences.includes('all') || app.audiences.includes(persona.role)); }
